// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBokmfcvL3PKvobiyAr2o7INJRLILOh97c',
    appId: '1:200269931567:web:374b30293d1826261f52da',
    messagingSenderId: '200269931567',
    projectId: 'fenix-313f9',
    authDomain: 'fenix-313f9.firebaseapp.com',
    storageBucket: 'fenix-313f9.appspot.com',
    measurementId: 'G-EYCG3D353Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBt_L0vzOZz0eSYoyb2ypHVIqgTy0UQmgg',
    appId: '1:200269931567:android:4cbdb7599efcee251f52da',
    messagingSenderId: '200269931567',
    projectId: 'fenix-313f9',
    storageBucket: 'fenix-313f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObjPG8eheOzX2F9kd-o8Dzg2tJ4xHLC4',
    appId: '1:200269931567:ios:8cbb7966993629d21f52da',
    messagingSenderId: '200269931567',
    projectId: 'fenix-313f9',
    storageBucket: 'fenix-313f9.appspot.com',
    iosClientId: '200269931567-0ss4f9cjpog87guhsd6t7bgbh88vkdq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fenixFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAObjPG8eheOzX2F9kd-o8Dzg2tJ4xHLC4',
    appId: '1:200269931567:ios:8cbb7966993629d21f52da',
    messagingSenderId: '200269931567',
    projectId: 'fenix-313f9',
    storageBucket: 'fenix-313f9.appspot.com',
    iosClientId: '200269931567-0ss4f9cjpog87guhsd6t7bgbh88vkdq6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fenixFlutter',
  );
}
